name: Compute Version
description: Computes a version for the current commit.
inputs:
  breaking-change:
    description: 'Has Breaking Change'
    required: true
  new-feature:
    description: 'Has New Feature'
    required: true
outputs:
  version:
    description: 'The computed version.'
    value: ${{ steps.compute_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install MinVer CLI
      uses: ./.github/actions/install-minver-cli
    - name: Compute Version
      id: compute_version
      shell: bash
      run: |
        if [ "${{ inputs.breaking-change }}" == "true" ]; then
          version=$(minver -v info -a major | tail -n 1)
        elif [ "${{ inputs.new-feature }}" == "true" ]; then
          version=$(minver -v info -a minor | tail -n 1)
        else
          version=$(minver -v info | tail -n 1)
        fi
        REGEX='^[0-9]+\.[0-9]+(\.[0-9]+)?'
        if [[ $version =~ $REGEX ]]; then
          version="${BASH_REMATCH[0]}"
        else
          version="0.0.0"
        fi
        echo "Computed version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT