name: Install .NET
description: Installs .NET (if not already installed).
inputs:
  dotnet-version:
    description: 'Target .NET version'
    required: true
    default: '9.0.x'
runs:
  using: "composite"
  steps:
    - name: Is .NET Already Installed?
      id: check_dotnet
      shell: bash
      run: |
        desired_version="${{ inputs.dotnet-version }}"
        desired_version_without_prefix="${desired_version%.x}"
        if dotnet --list-sdks | grep -E "^$desired_version_without_prefix"; then
          echo "dotnet_installed=true" >> $GITHUB_OUTPUT
        else
          echo "dotnet_installed=false" >> $GITHUB_OUTPUT
        fi
    - name: Install .NET
      if: steps.check_dotnet.outputs.dotnet_installed == 'false'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}