name: Create and Release NuGet
description: Creates and releases the NuGet files.
inputs:
  breaking-change:
    description: 'Has Breaking Change'
    required: true
  new-feature:
    description: 'Has New Feature'
    required: true
runs:
  using: "composite"
  steps:
  - name: Build and Test
    uses: ./.github/actions/build-and-test
  - name: Compute Version
    id: compute_version
    uses: ./.github/actions/compute-version
    with:
      breaking-change: ${{ inputs.breaking-change }}
      new-feature: ${{ inputs.new-feature }}
  - name: Create Tag
    uses: ./.github/actions/create-tag
    with:
      tag: ${{ steps.compute_version.outputs.version }}
  - name: Create NuGet Package
    shell: bash
    run: dotnet pack --no-restore --configuration Release --output ./nuget-output -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    env:
      MinVerVerbosity: normal
  - name: Create GitHub Release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    shell: bash
    run: |
      version=${{ steps.compute_version.outputs.version }}
      gh release create $version --title "Release $version" ./nuget-output/*