name: Build and Test
description: Builds and tests the project.
runs:
  using: "composite"
  steps:
  - name: Checkout Repository
    uses: ./.github/actions/checkout
  - name: Install .NET
    uses: ./.github/actions/install-dotnet
  - name: Install Dependencies
    shell: bash
    run: dotnet restore
  - name: Build
    shell: bash
    run: dotnet build --no-restore
    env:
      MinVerVerbosity: normal
  - name: Test
    shell: bash
    run: dotnet test --no-restore
