name: Build Phaeyz.Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/lib/build.yml
    with:
      package-name: 'Phaeyz.Testing'