name: Build Phaeyz.Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/lib-build-and-test.yml
    with:
      package-name: 'Phaeyz.Testing'