name: Build Phaeyz.Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-restore

    - name: Publish
      run: dotnet publish --no-restore --output ./publish ./Phaeyz.Testing

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish