name: Build Phaeyz.Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PACKAGE_NAME: Phaeyz.Testing

jobs:
  build:
    uses: ./.github/workflows/build-steps.yml
    with:
      package-name: ${{ env.PACKAGE_NAME }}