name: Build and Release Phaeyz.Testing

on:
  workflow_dispatch:
    inputs:
      breaking-change:
        description: 'Is this an improvement with breaking changes?'
        required: true
        type: boolean
      new-feature:
        description: 'Does this add new features?'
        required: true
        type: boolean

jobs:
  versioning:
    uses: ./.github/workflows-lib/create-version-tag.yml
    with:
      breaking_change: ${{ github.event.inputs.breaking-change == 'true' }}
      new_feature: ${{ github.event.inputs.new-feature == 'true' }}

  build:
    needs: versioning
    uses: ./.github/workflows-lib/build.yml
    with:
      package-name: 'Phaeyz.Testing'

  release:
    needs: [versioning, build]
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: 'Phaeyz.Testing'
        path: ./publish

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        NEW_TAG=${{ needs.versioning.outputs.new_tag }}
        gh release create $NEW_TAG --title "Release $NEW_TAG" ./publish/*