name: Build and Release Phaeyz.Testing

on:
  workflow_dispatch:
    inputs:
      breaking-change:
        description: 'Has Breaking Change'
        required: true
        type: boolean
      new-feature:
        description: 'Has New Feature'
        required: true
        type: boolean

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
    - name: Build and Test
      uses: ./.github/workflows/lib-build-and-test.yml

    - name: Create Version Tag
      id: create_version_tag
      uses: ./.github/workflows/lib-create-version-tag.yml
      with:
        breaking-change: ${{ github.event.inputs.breaking-change == 'true' }}
        new-feature: ${{ github.event.inputs.new-feature == 'true' }}

    - name: Test
      run: |
        version=${{ steps.create_version_tag.outputs.version }}
        echo "version = $version"
        echo "version2 = ${{ steps.create_version_tag.outputs.version }}"

    - name: Create and Relase NuGet
      uses: ./.github/workflows/lib-create-and-release-nuget.yml
      with:
        package-name: 'Phaeyz.Testing'
        version: ${{ needs.create-version-tag.outputs.version }}