name: Build and Release Phaeyz.Testing

on:
  workflow_dispatch:
    inputs:
      breaking-change:
        description: 'Has Breaking Change'
        required: true
        type: boolean
      new-feature:
        description: 'Has New Feature'
        required: true
        type: boolean

jobs:
  build-and-test:
    uses: ./.github/workflows/lib-build-and-test.yml
    with:
      package-name: 'Phaeyz.Testing'

  create-version-tag:
    needs: build-and-test
    uses: ./.github/workflows/lib-create-version-tag.yml
    with:
      breaking-change: ${{ github.event.inputs.breaking-change == 'true' }}
      new-feature: ${{ github.event.inputs.new-feature == 'true' }}

  create-and-release-nuget:
    needs: create-version-tag
    uses: ./.github/workflows/lib-create-and-release-nuget.yml
    with:
      package-name: 'Phaeyz.Testing'
      version: ${{ needs.create-version-tag.outputs.version }}