name: Build and Release Phaeyz.Testing

on:
  workflow_dispatch:
    inputs:
      breaking-change:
        description: 'Has Breaking Change'
        required: true
        type: boolean
      new-feature:
        description: 'Has New Feature'
        required: true
        type: boolean

jobs:
  versioning:
    uses: ./.github/workflows/lib-create-version-tag.yml
    permissions:
      contents: write
    with:
      breaking-change: ${{ github.event.inputs.breaking-change == 'true' }}
      new-feature: ${{ github.event.inputs.new-feature == 'true' }}

  build:
    needs: versioning
    uses: ./.github/workflows/lib-build.yml
    with:
      package-name: 'Phaeyz.Testing'

  release:
    needs: [versioning, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: 'Phaeyz.Testing'
        path: ./publish

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        NEW_TAG=${{ needs.versioning.outputs.new_tag }}
        gh release create $NEW_TAG --title "Release $NEW_TAG" ./publish/*