name: ~Lib~ Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        type: string
        default: '9.0.x'
      publish-output:
        type: string
        default: './publish'
      package-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Install MinVer CLI
      run: dotnet tool install --global minver-cli

    - name: MinVer Help
      run: minver --help
      env:
        MinVerVerbosity: info

    - name: Compute Version
      id: compute_version
      run: |
        breaking-change: true
        new-feature: false
        if [ "$breaking-change" == "true" ]; then
          version=$(minver -v info -a major | tail -n 1)
        elif [ "$new-feature" == "true" ]; then
          version=$(minver -v info -a minor | tail -n 1)
        else
          version=$(minver -v info | tail -n 1)
        fi
        echo "Computed version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Display Computed Version
      run: echo "Computed version is ${{ steps.compute_version.outputs.version }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      env:
        MinVerVerbosity: normal

    - name: Test
      run: dotnet test --no-restore

    - name: Publish
      run: dotnet publish --no-restore --output ${{ inputs.publish-output }} ./${{ inputs.package-name }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package-name }}
        path: ${{ inputs.publish-output }}